services:
  database:
    image: postgres:17
    ports:
      - 5432:5432
    volumes:
      - rps-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres

volumes:
  rps-postgres:
