basePath: /
definitions:
  matchmaker.Room:
    properties:
      address:
        type: string
      code:
        type: string
      createdAt:
        type: string
      gamePort:
        type: integer
      id:
        type: integer
      maxPlayers:
        type: integer
      name:
        type: string
      players:
        type: integer
      private:
        type: boolean
      queryPort:
        type: integer
      updatedAt:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: fbshamiladze@gmail.com
    name: Nika Shamiladze
  description: Game V0 API
  title: Game V0 API
  version: "1.0"
paths:
  /api/v1/rooms:
    get:
      consumes:
      - application/json
      description: List all rooms
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/matchmaker.Room'
            type: array
      summary: List all rooms
    post:
      consumes:
      - application/json
      description: Create a new room
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/matchmaker.Room'
      summary: Create a new room
  /api/v1/rooms/{code}:
    get:
      consumes:
      - application/json
      description: Get a room
      parameters:
      - description: Room code
        in: path
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/matchmaker.Room'
      summary: Get a room
swagger: "2.0"
